apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
    - name: goserver
      image: "amandasdn/hello-amanda:latest"
      ports:
        - containerPort: 80
